#WORLD                       = (1700, 850)
#SCREEN                      = (1700, 850)
WORLD                       = (1200, 750)
SCREEN                      = (1200, 750)
PLANT_MAX_SIZE              = 6
PLANT_GROWTH                = 0.6
PLANT_INIT_NUM              = 100
PLANT_LIFE                  = 500
PLANT_MULTIPLY              = 0.04
CREATURE_MULTIPLY           = 0.002
EAT                         = 1
CREATURE_INIT_NUM           = 50
BASE_ENERGY                 = 0.001
MOVE_ENERGY                 = 0.003
REP_TIME                    = 20
REP_ENERGY                  = 0.4
SPEED                       = 1
TURN                        = 0.1
SENSOR_SPEED                = 1
REPRODUCTION_TIME           = 60
CREATURE_MIN_SIZE           = 3
CREATURE_MAX_SIZE           = 7
HIT                         = 300
# colors
BROWN = (110, 50, 9)
LIME = (127, 255, 0)
