TITLE = 'NATURE v0.2.3'
SUBTITLE = "2019-2021 Artur Gwoździowski"
#WORLD                       = (1700, 850)
#SCREEN                      = (1700, 850)
#FONT_SIZE                   = 16
WORLD                       = (1500, 750)
SCREEN                      = (1500, 750)
FONT_SIZE                   = 10
PLANT_MAX_SIZE              = 9
PLANT_GROWTH                = 0.6
PLANT_INIT_NUM              = 50
PLANT_LIFE                  = 500
PLANT_MULTIPLY              = 0.04
CREATURE_MULTIPLY           = 0.002
EAT                         = 50
CREATURE_INIT_NUM           = 40
BASE_ENERGY                 = 0.001
MOVE_ENERGY                 = 0.003
REP_TIME                    = 20
REP_ENERGY                  = 0.4
SPEED                       = 1
TURN                        = 0.1
SENSOR_SPEED                = 1
REPRODUCTION_TIME           = 60
CREATURE_MIN_SIZE           = 3
CREATURE_MAX_SIZE           = 7
HIT                         = 300
# colors
BROWN = (110, 50, 9)
LIME = (127, 255, 0)
